#BasicBoard v0.7
#
#Local varibales which working without PlaceholderAPI, I want to add more
#{player_name}
#{prefix} - (plugin prefix).
#{<worldname>_online_players} Online players in specific world'
#{player_ping}
#{player_world}
#{player_exp}
#{player_hp}
#{player_food}
#{player_kills}
#{player_deaths}
#{mob_kills}
#
#Vault placeholders: Needed vault for work!
#{player_balance}
#{player_group}
#{player_prefix}
#{player_suffix}
#
#
#FOR MORE PLACEHOLDERS https://github.com/Fighter20000/basicboard/wiki/Placeholders

#Recommended enable it, for lot of cool placeholders!
PlaceholderAPI:
  enable: true

BoardSettings:
  enable-board: true
  #time in second
  scoreboard-update: 1
  #You can use prefix at anywhere with {prefix} variable
  board-prefix: "&7[&aBasic&2Board&7]"

#You can disable board in a specific world!
disable-worlds:
  - 'test'
  - 'exampleworld'

#Scoreboard header
scoreboard-displayname: 
  - '&aB'
  - '&aBa'
  - '&aBas'
  - '&aBasi'
  - '&aBasic'
  - '&aBasic&2B'
  - '&aBasic&2Bo'
  - '&aBasic&2Boa'
  - '&aBasic&2Boar'
  - '&aBasic&2Board'

#At this time you can't animate lines!
scoreboard:
  text:
    - '&f&m+------------------------+'
    - ''
    - '&7Welcome, &a{player_name}'
    - '&r'
    - '&7Ping: &a{player_ping}'
    - '&7World: &a{player_world}'
    - ''
    - '&7Online: &a{server_online}&8/&a{server_max_online}'
    - '&f&f&m+------------------------+'



