name: Scoreboard
main: com.fighter.scoreboard.Main.Main
version: v0.3
author: Fighter20000
softdepend: [Vault, PlaceholderAPI]
commands:
  basicboard:
    default: false
    description: Main command of BasicBoard.
